export const PerfilEnum = {
    DEPENDIENTE: 'DEPENDIENTE',
    TRABAJADOR: 'TRABAJADOR',
    INDEPENDIENTE: 'INDEPENDIENTE',
    ESPORADICO: 'ESPORADICO'
};

export const EstadoJuegoEnum = {
    EN_CURSO: 'EN_CURSO',
    GAME_OVER: 'GAME_OVER',
    COMPLETADO: 'COMPLETADO'
};

