export const PerfilEnum = {
    DEPENDIENTE: 'DEPENDIENTE',
    TRABAJADOR: 'TRABAJADOR',
    INDEPENDIENTE: 'INDEPENDIENTE',
    ESPORADICO: 'ESPORADICO',
    NINI: 'NINI'
};

export const EstadoJuegoEnum = {
    EN_CURSO: 'EN_CURSO',
    GAME_OVER: 'GAME_OVER',
    COMPLETADO: 'COMPLETADO'
};

export const LocalizacionEnum = {
    ESCUELA: 'ESCUELA',
    TRANSPORTE: 'TRANSPORTE',
    CONSULTORIO: 'CONSULTORIO',
    CENTRO_COMERCIAL: 'CENTRO_COMERCIAL',
    RECAMARA: 'RECAMARA',
    SUPERMERCADO: 'SUPERMERCADO',
    CASA_OFICINA: 'CASA_OFICINA'
};
